simpleHarvest:
  materials: []
  activated: false
advancedCompost:
  materials: []
  activated: false
mutedPlayers:
  players: []
  activated: false
privateMessageViewing:
  admins: []
  activated: false
SendCoordsOfDeathOnRespawn: false
SendMessageOnGamemodeChange: false
UnlimitedAnvil: false
villagerSelect:
  activated: true
  cooldown: 1
  maxRetries: 700
CtrlQCraft: false
FastLeafDecay: false
ToolBreakPrevention: false
